name: Source Control Demo
on: 
  push:
    branches:
      - 'main'

jobs:
    
  build:
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout from repository
        uses: actions/checkout@v3
        
      - name: Get changed files
        id: changed-files-specific
        uses: tj-actions/changed-files@v34
        with:
          files: | 
            **.json
            
      - name: Create WOFL folder
        run: mkdir wofl
        
      - name: Move changed files to WOFL folder
        run: mv **.json ./wofl
          
      - name: Auto-generate wofl files
        run:  mv ./wofl/**.json **.wofl
        
       
      - name: Configure METL credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'
      
      - name: Deploy changes to METL
        id: aws-deploy-s3
        uses: oneyedev/aws-deploy-s3@v2
        with:
          region: 'us-east-1'
          bucket: 'source-control-demo'
          source: './wofl'
          target: 's3://source-control-demo/test-folder/'
          
  success:
      needs:  deploy

      runs-on: ubuntu-latest

      steps:
        - name: Show outcome
          run: echo 'Changes successfully deployed to METL'
