name: Schedule Jobs on Prod
on:
  push:
    branches: [ "main" ]

jobs:
    
  validate_response:
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout from repository
        uses: actions/checkout@v3
            
      - name: Initiate connection to Matillion
        run: mkdir build
      
      - name: Authenticate with credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'
          
      - name: Execute build action
        run: mkdir newbuild
  
      - name: status
        run: echo 'build successful'
        
  create_PR:
    needs:  validate_response
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout build
        uses: actions/checkout@v3
       
      - name: Configure Matillion credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'
      
      - name: Publish changes to Matillion
        id: aws-deploy-s3
        uses: oneyedev/aws-deploy-s3@v2
        with:
          region: 'us-east-1'
          bucket: 'source-control-demo'
          source: './build'
          target: 's3://source-control-demo/test-folder/'   


  status_check:
    needs:  validate_response
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout build
        uses: actions/checkout@v3
       
      - name: Configure Matillion credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'
      
      - name: Publish changes to Matillion
        id: aws-deploy-s3
        uses: oneyedev/aws-deploy-s3@v2
        with:
          region: 'us-east-1'
          bucket: 'source-control-demo'
          source: './build'
          target: 's3://source-control-demo/test-folder/'
  
  linear_history:
    needs:  validate_response

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout build
        uses: actions/checkout@v3
       
      - name: Configure Matillion credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'
      
      - name: Publish changes to Matillion
        id: aws-deploy-s3
        uses: oneyedev/aws-deploy-s3@v2
        with:
          region: 'us-east-1'
          bucket: 'source-control-demo'
          source: './build'
          target: 's3://source-control-demo/test-folder/'
          
  merge_dev_to_prod:
    needs:  [create_PR, status_check, linear_history]

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout build
        uses: actions/checkout@v3
       
      - name: Configure Matillion credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'
      
      - name: Publish changes to Matillion
        id: aws-deploy-s3
        uses: oneyedev/aws-deploy-s3@v2
        with:
          region: 'us-east-1'
          bucket: 'source-control-demo'
          source: './build'
          target: 's3://source-control-demo/test-folder/' 
  
  schedule_job_on_Matillion:
    needs:  merge_dev_to_prod

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout build
        uses: actions/checkout@v3
       
      - name: Configure Matillion credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'
      
      - name: Publish changes to Matillion
        id: aws-deploy-s3
        uses: oneyedev/aws-deploy-s3@v2
        with:
          region: 'us-east-1'
          bucket: 'source-control-demo'
          source: './build'
          target: 's3://source-control-demo/test-folder/'
          
  success:
    needs:  schedule_job_on_Matillion

    runs-on: ubuntu-latest
    
    steps:
      - name: status
        run: echo "Scheduled successfully"
